### ISSUE TITLE
Uninitialized constant ActiveRecord::AttributeSet when restoring with rails 5.2 a draft made with rails 5.1 - Any hint?

### ISSUE THREAD

**Issue by shadowed87** [ledermann/drafting#10]
As the title suggests, I have in production many drafts made with the current rails deployed (5.1), but now I want to upgrade to Rails 5.2...
During my tests I came across this issue when doing draft.restore 

uninitialized constant ActiveRecord::AttributeSet

Any hint on how to overcome this?

Thank you in advance

**Comment by ledermann** [comment]
Hm, [ActiveRecord::AttributeSet](https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/attribute_set/builder.rb) doesn't exist anymore in Rails 5.2. Because of using `Marshal.dump` by default, a reference to this class is stored inside the `data` column.

Maybe you can fix this by defining a mock like this:

```ruby
module ActiveRecord
  class AttributeSet
  end
end
```
